// Code generated by protoc-gen-go. DO NOT EDIT.
// V2Ray-compatible GeoIPList (geoip.dat). Source: Loyalsoldier/geoip plugin/v2ray/geoip.proto
// Package renamed to geoip for this module.

package geoip

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type v2rayCIDR struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ip     []byte `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Prefix uint32 `protobuf:"varint,2,opt,name=prefix,proto3" json:"prefix,omitempty"`
}

func (x *v2rayCIDR) Reset() {
	*x = v2rayCIDR{}
	mi := &file_geoip_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *v2rayCIDR) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*v2rayCIDR) ProtoMessage() {}

func (x *v2rayCIDR) ProtoReflect() protoreflect.Message {
	mi := &file_geoip_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (*v2rayCIDR) Descriptor() ([]byte, []int) {
	return file_geoip_proto_rawDescGZIP(), []int{0}
}

func (x *v2rayCIDR) GetIp() []byte {
	if x != nil {
		return x.Ip
	}
	return nil
}

func (x *v2rayCIDR) GetPrefix() uint32 {
	if x != nil {
		return x.Prefix
	}
	return 0
}

type v2rayGeoIPEntry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CountryCode string       `protobuf:"bytes,1,opt,name=country_code,json=countryCode,proto3" json:"country_code,omitempty"`
	Cidr        []*v2rayCIDR `protobuf:"bytes,2,rep,name=cidr,proto3" json:"cidr,omitempty"`
}

func (x *v2rayGeoIPEntry) Reset() {
	*x = v2rayGeoIPEntry{}
	mi := &file_geoip_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *v2rayGeoIPEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*v2rayGeoIPEntry) ProtoMessage() {}

func (x *v2rayGeoIPEntry) ProtoReflect() protoreflect.Message {
	mi := &file_geoip_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (*v2rayGeoIPEntry) Descriptor() ([]byte, []int) {
	return file_geoip_proto_rawDescGZIP(), []int{1}
}

func (x *v2rayGeoIPEntry) GetCountryCode() string {
	if x != nil {
		return x.CountryCode
	}
	return ""
}

func (x *v2rayGeoIPEntry) GetCidr() []*v2rayCIDR {
	if x != nil {
		return x.Cidr
	}
	return nil
}

type v2rayGeoIPList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Entry []*v2rayGeoIPEntry `protobuf:"bytes,1,rep,name=entry,proto3" json:"entry,omitempty"`
}

func (x *v2rayGeoIPList) Reset() {
	*x = v2rayGeoIPList{}
	mi := &file_geoip_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *v2rayGeoIPList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*v2rayGeoIPList) ProtoMessage() {}

func (x *v2rayGeoIPList) ProtoReflect() protoreflect.Message {
	mi := &file_geoip_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (*v2rayGeoIPList) Descriptor() ([]byte, []int) {
	return file_geoip_proto_rawDescGZIP(), []int{2}
}

func (x *v2rayGeoIPList) GetEntry() []*v2rayGeoIPEntry {
	if x != nil {
		return x.Entry
	}
	return nil
}

var File_geoip_proto protoreflect.FileDescriptor

var file_geoip_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x67, 0x65, 0x6f, 0x69, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x12, 0x67,
	0x65, 0x6f, 0x69, 0x70, 0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2e, 0x76, 0x32, 0x72, 0x61,
	0x79, 0x22, 0x2e, 0x0a, 0x04, 0x43, 0x49, 0x44, 0x52, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x70, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x02, 0x69, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x72, 0x65,
	0x66, 0x69, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x70, 0x72, 0x65, 0x66, 0x69,
	0x78, 0x22, 0x58, 0x0a, 0x05, 0x47, 0x65, 0x6f, 0x49, 0x50, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x72, 0x79, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x2c, 0x0a,
	0x04, 0x63, 0x69, 0x64, 0x72, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x67, 0x65,
	0x6f, 0x69, 0x70, 0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2e, 0x76, 0x32, 0x72, 0x61, 0x79,
	0x2e, 0x43, 0x49, 0x44, 0x52, 0x52, 0x04, 0x63, 0x69, 0x64, 0x72, 0x22, 0x3c, 0x0a, 0x09, 0x47,
	0x65, 0x6f, 0x49, 0x50, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x2f, 0x0a, 0x05, 0x65, 0x6e, 0x74, 0x72,
	0x79, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x67, 0x65, 0x6f, 0x69, 0x70, 0x2e,
	0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2e, 0x76, 0x32, 0x72, 0x61, 0x79, 0x2e, 0x47, 0x65, 0x6f,
	0x49, 0x50, 0x52, 0x05, 0x65, 0x6e, 0x74, 0x72, 0x79, 0x42, 0x2c, 0x5a, 0x2a, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x4c, 0x6f, 0x79, 0x61, 0x6c, 0x73, 0x6f, 0x6c,
	0x64, 0x69, 0x65, 0x72, 0x2f, 0x67, 0x65, 0x6f, 0x69, 0x70, 0x2f, 0x70, 0x6c, 0x75, 0x67, 0x69,
	0x6e, 0x2f, 0x76, 0x32, 0x72, 0x61, 0x79, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_geoip_proto_rawDescOnce sync.Once
	file_geoip_proto_rawDescData = file_geoip_proto_rawDesc
)

func file_geoip_proto_rawDescGZIP() []byte {
	file_geoip_proto_rawDescOnce.Do(func() {
		file_geoip_proto_rawDescData = protoimpl.X.CompressGZIP(file_geoip_proto_rawDescData)
	})
	return file_geoip_proto_rawDescData
}

var file_geoip_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_geoip_proto_goTypes = []interface{}{
	(*v2rayCIDR)(nil),       // 0: geoip.plugin.v2ray.CIDR
	(*v2rayGeoIPEntry)(nil), // 1: geoip.plugin.v2ray.GeoIP
	(*v2rayGeoIPList)(nil),  // 2: geoip.plugin.v2ray.GeoIPList
}
var file_geoip_proto_depIdxs = []int32{
	0, // 0: geoip.plugin.v2ray.GeoIP.cidr:type_name -> geoip.plugin.v2ray.CIDR
	1, // 1: geoip.plugin.v2ray.GeoIPList.entry:type_name -> geoip.plugin.v2ray.GeoIP
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_geoip_proto_init() }
func file_geoip_proto_init() {
	if File_geoip_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_geoip_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_geoip_proto_goTypes,
		DependencyIndexes: file_geoip_proto_depIdxs,
		MessageInfos:      file_geoip_proto_msgTypes,
	}.Build()
	File_geoip_proto = out.File
	file_geoip_proto_rawDesc = nil
	file_geoip_proto_goTypes = nil
	file_geoip_proto_depIdxs = nil
}
